name: Build / Containerize

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install NBGV
        run: dotnet tool install --tool-path . nbgv

      - name: Get NBGV Version
        id: nbgv-version
        run: |
          c_version=$(nbgv get-version -v SimpleVersion -f text)
          echo "package version = ${c_version}"
          echo "C_VERSION=${c_version}" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: .NET Publish
        env:
          ESCAPED_TAGS: "'\"${{ steps.nbgv-version.outputs.C_VERSION }};latest\"'"
        run: dotnet publish --os linux --arch x64 -c Release -p:ContainerImageTags=${{ env.ESCAPED_TAGS }} -p:PublishProfile=DefaultContainer